import { describe, expect, test } from "bun:test";
import { parseWorkflowScript, WorkflowParseError } from "./parser";

describe("dynamic workflow parser", () => {
  test("parses a valid workflow script whose first statement exports literal meta", () => {
    const parsed = parseWorkflowScript(`
      export const meta = {
        name: "repo_review",
        description: "Review the repository with parallel subagents",
        phases: [
          { title: "Review" },
          { title: "Verify", description: "Validate candidate findings" },
          { title: "Synthesize" },
        ],
      };

      phase("Review");
      const result = await agent("Inspect the repository");
      return { result };
    `);

    expect(parsed.meta).toEqual({
      name: "repo_review",
      description: "Review the repository with parallel subagents",
      phases: [
        { title: "Review" },
        { title: "Verify", description: "Validate candidate findings" },
        { title: "Synthesize" },
      ],
    });
    expect(parsed.executableScript).not.toContain("export const meta");
    expect(parsed.executableScript).toContain('phase("Review")');
  });

  test("allows comments and whitespace before the first meta statement", () => {
    const parsed = parseWorkflowScript(`
      // generated by the agent
      /* reviewed by parser */
      export const meta = {
        name: "tiny",
        description: "Tiny workflow",
        phases: [{ title: "Run" }],
      }

      return await agent("Do the tiny workflow");
    `);

    expect(parsed.meta.name).toBe("tiny");
    expect(parsed.meta.phases).toEqual([{ title: "Run" }]);
  });

  test.each([
    {
      name: "object spread",
      script: `export const meta = { ...baseMeta, name: "bad", phases: [{ title: "Run" }] };`,
    },
    {
      name: "array spread",
      script: `export const meta = { name: "bad", phases: [...phases] };`,
    },
    {
      name: "computed key",
      script: `export const meta = { [nameKey]: "bad", phases: [{ title: "Run" }] };`,
    },
    {
      name: "method property",
      script: `export const meta = { name() { return "bad" }, phases: [{ title: "Run" }] };`,
    },
    {
      name: "function call",
      script: `export const meta = makeMeta();`,
    },
    {
      name: "non-meta export",
      script: `export const meta = { name: "bad", phases: [{ title: "Run" }] }; export const other = 1;`,
    },
    {
      name: "unsafe key",
      script: `export const meta = { name: "bad", __proto__: {}, phases: [{ title: "Run" }] };`,
    },
  ])("rejects non-literal meta: $name", ({ script }) => {
    expect(() => parseWorkflowScript(script)).toThrow(WorkflowParseError);
  });

  test.each([
    {
      name: "string phase entry",
      script: `export const meta = { name: "bad", phases: ["Run"] };`,
      repair: '{ title: "Run" }',
      rejectedShape: 'phases: ["Run"]',
    },
    {
      name: "name phase field",
      script: `export const meta = { name: "bad", phases: [{ name: "Run" }] };`,
      repair: '{ title: "Run" }',
      rejectedShape: '{ name: "Run" }',
    },
  ])("rejects invalid phase shapes with repair guidance: $name", ({
    script,
    repair,
    rejectedShape,
  }) => {
    const message = captureParseErrorMessage(script);
    expect(message).toContain(repair);
    expect(message).toContain(rejectedShape);
  });

  test.each([
    {
      name: "long string phase entry",
      script: `export const meta = { name: "bad", phases: [${JSON.stringify("x".repeat(500))}] };`,
    },
    {
      name: "long name phase field",
      script: `export const meta = { name: "bad", phases: [{ name: ${JSON.stringify("x".repeat(500))} }] };`,
    },
  ])("keeps invalid phase diagnostics concise: $name", ({ script }) => {
    const message = captureParseErrorMessage(script);
    expect(message.length).toBeLessThan(260);
    expect(message).toContain("…");
    expect(message).toContain('{ title: "Run" }');
    expect(message).not.toContain("x".repeat(120));
  });

  test.each([
    {
      name: "Date.now",
      script: `export const meta = { name: "bad", phases: [{ title: "Run" }] }; const stamp = Date.now(); return await agent(String(stamp));`,
    },
    {
      name: "Math.random",
      script: `export const meta = { name: "bad", phases: [{ title: "Run" }] }; const id = Math.random(); return await agent(String(id));`,
    },
    {
      name: "argument-less new Date",
      script: `export const meta = { name: "bad", phases: [{ title: "Run" }] }; const now = new Date(); return await agent(now.toISOString());`,
    },
    {
      name: "Date.now inside template interpolation",
      script: `export const meta = { name: "bad", phases: [{ title: "Run" }] }; const stamp = \`\${Date.now()}\`; return await agent(stamp);`,
    },
    {
      name: "Math.random inside nested template interpolation",
      script: `export const meta = { name: "bad", phases: [{ title: "Run" }] }; const id = \`\${\`\${Math.random()}\`}\`; return await agent(id);`,
    },
    {
      name: "argument-less new Date inside template interpolation",
      script: `export const meta = { name: "bad", phases: [{ title: "Run" }] }; return await agent(\`\${new Date()}\`);`,
    },
  ])("rejects nondeterministic workflow code: $name", ({ script }) => {
    expect(() => parseWorkflowScript(script)).toThrow(WorkflowParseError);
  });
});

function captureParseErrorMessage(script: string): string {
  try {
    parseWorkflowScript(script);
  } catch (error) {
    if (!(error instanceof WorkflowParseError)) throw error;
    return error.message;
  }

  throw new Error("expected WorkflowParseError");
}
